apiVersion: v1
kind: ConfigMap # Tipo: um mapa de configurações
metadata:
  name: prometheus-config # Nome do ConfigMap
data:
  # O nome do arquivo que será criado dentro do container
  prometheus.yml: |
    global:
      # Define o intervalo padrão para buscar métricas
      scrape_interval: 15s 

    # Lista de "jobs" (trabalhos) que o Prometheus vai monitorar
    scrape_configs:
      - job_name: 'trabalho'
        static_configs:
          - targets: ['trabalho:3123'] # Onde o Prometheus roda
