# Define os "destinos" (serviços do Kubernetes)
upstream app-server {
  # 'trabalho' é o nome do seu K8S/service.yaml
  server trabalho:3123;
}

upstream grafana-server {
  # 'grafana' é o nome do seu K8S/grafana-service.yaml
  server grafana:3000;
}

upstream prometheus-server {
  # 'prometheus-service' é o nome do seu K8S/prometheus-deployment.yaml
  server prometheus-service:9090;
}

# Configuração principal do servidor NGINX
server {
  # O NGINX vai "ouvir" na porta 80
  listen 80;

  # Rota para a Aplicação Principal
  location / {
    proxy_pass http://app-server;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Rota para o Grafana (CORRIGIDA)
  location /grafana/ {
    # A barra '/' no final do proxy_pass é crucial!
    proxy_pass http://grafana-server/; 
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Rota para o Prometheus (CORRIGIDA)
  location /prometheus/ {
    # A barra '/' no final do proxy_pass também é crucial!
    proxy_pass http://prometheus-server/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}